### ISSUE TITLE
change, allow adding multiple excel files as new dist groups, instead of all in one

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#194] opened 2020-05-29 02:39 UTC
sorry about this... after the client has been using the system, he thinks allowing multiple excel files for dist lists. In this case, we will also need the ability to remove the lists.

**Comment by ctyar** [comment] 2020-06-01 14:07
Duplicate of https://github.com/whynotearth/meredith-core/issues/195

**Closed by ctyar** 2020-06-01 14:07 UTC
Labels: .net
