### ISSUE TITLE
Brow Tricks Service Categories

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#117] opened 2020-03-17 04:06 UTC
Meredith core needs to deploy salon owner (subscriber) websites for Brow Tricks #112 . Once a new account is created by a salon owner, they will enter in some basic business info and Meredith core will build and deploy webite for them. 

The prototype of the pages can be found [here](https://www.figma.com/proto/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=1311%3A29949&viewport=352%2C3300%2C0.17357392609119415&scaling=scale-down)
To see the booking pages, click "test client booking" or "test referral booking" 

### Categories 
The category page is a page where customers can view and choose the service categories they're interested in. They first choose the category of services they would like to view, which leads to a list of services in that category. The service page backend issue is #116 
![image](https://user-images.githubusercontent.com/5694308/77315955-16214a80-6d3b-11ea-9dcb-bf0996fba823.png)

Build `moduleSalon` database, and a table of categories linked to services in each category 

### Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Prototype" page contains all the screens necessary for the app

**Comment by paulchrisluke** [comment] 2020-04-13 02:46
related: https://github.com/whynotearth/meredith-core/issues/134

**Comment by ctyar** [comment] 2020-04-13 07:56
Duplicate of #134

**Closed by ctyar** 2020-04-13 07:56 UTC
Labels: .net
