### ISSUE TITLE
Brow Tricks Business Hours Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#115] opened 2020-03-17 03:31 UTC
Meredith core needs to deploy salon owner (subscriber) websites for Brow Tricks #112 . Once a new account is created by a salon owner, they will enter in some basic business info and Meredith core will build and deploy webite for them. This issue is for the Business Hours Page. 

The prototype of the pages can be found [here](https://www.figma.com/proto/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=1311%3A29949&viewport=352%2C3300%2C0.17357392609119415&scaling=scale-down)
To see the booking pages, click "test client booking" or "test referral booking" 

### Business Hours
This page display business hours for the subscriber's site. 
![image](https://user-images.githubusercontent.com/5694308/76749312-e60fff80-67ae-11ea-888a-915ea9b681b4.png)

We will need a "business hour" table attached to the company table in our database. This information will be collected when subscribers first create an account, and will be editable within the Brow Tricks app 

### Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Prototype" page contains all the screens necessary for the app

**Comment by ctyar** [comment] 2020-04-17 08:01
Duplicate of https://github.com/whynotearth/meredith-core/issues/152

**Closed by ctyar** 2020-04-17 08:01 UTC
Labels: .net
