### ISSUE TITLE
add page category weight

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#106] opened 2020-03-13 01:54 UTC
In preperation to automate our email building for volkswagen, I will need a column added to our page category table to assign a 0-100 value.

Right now, I will manually assigning category weight. But that will be automated over time. For now, I just need every category to deploy with a given weight, so I can use that to trian the automation.

Example:

"Priority" category would have a weight of 100, since I always want it at the top. 
"People" category could have a weight of 10, since it is a low value thing to display.

![image](https://user-images.githubusercontent.com/5694308/76582167-141fe600-6508-11ea-88f7-ff0b69dda36d.png)

Eventually in automated, I will tell meredith-core to layout the email based on priority and total conversions (email reads). But that will be later. Right now, we just need to start adding that weight in so we can collect that data and play with it.

**Comment by paulchrisluke** [comment] 2020-04-06 18:08
@KennethA1000 this may be another good one for you. its adding one more column to our category table `weight`. We will only use this for volkswagen for now, and will manually insert the values, but this will eventually be used by our ai to auto generate email compositions.

**Comment by ctyar** [comment] 2020-04-14 08:12
Duplicate of https://github.com/whynotearth/meredith-core/issues/143

**Closed by ctyar** 2020-04-14 08:12 UTC
Labels: .net
