### ISSUE TITLE
No redirect back to app if OAuth verification is cancelled

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#52] opened 2019-10-20 05:57 UTC
**Steps to reproduce the issue:**  

1. Select any OAuth service for sign up/login.  

2.  Click on cancel. 
![image](https://user-images.githubusercontent.com/34229217/67155398-1c467180-f32c-11e9-85e3-e5838053fb5f.png)   
  
4. It doesn't redirect back to the app.
![image](https://user-images.githubusercontent.com/34229217/67155401-3da75d80-f32c-11e9-9594-600b3cb8f9b1.png)

It can be tested at https://staging.vkirirom.com/

**Expected Behaviour:**  
Upon failed authentication, it should take the user to the `returnURL`

**Comment by StrangeWill** [comment] 2019-10-25 12:05
It _looks_ like this one:

```
Traceback (most recent call last):
1
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1+<HandleRequestAsync>d__12.MoveNext()
2
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
3
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
4
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
5
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
6
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware+<Invoke>d__13.MoveNext()
7
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
8
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__185`1.MoveNext()
Exception: An error was encountered while handling the remote login.
Traceback (most recent call last):
Exception: access_denied;Description=Permissions error
```

Looks like we just need to configure the `o.Events.OnRemoteFailure` on our oauth provider to do something. Do need to kind of determine _what_ that something is, we need to tell the application that the user bailed out of logging in.

**Comment by atharva3010** [comment] 2019-10-25 16:17
Yeah, could we redirect to the `returnURL` provided by the client side?

**Comment by paulchrisluke** [comment] 2019-11-13 08:58
from @atharva3010 for history:
I am seeing this weird CORS error while authenticating via the vkirirom app

```
Access to XMLHttpRequest at 'https://stagingapi.whynot.earth/Account/AccessDenied?ReturnUrl=%2Fapi%2Fv0%2Fauthentication%2Fping' (redirected from 'https://stagingapi.whynot.earth/api/v0/authentication/ping') from origin 'https://staging.vkirirom.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

this was working fine a few weeks ago when I last checked
no commits have been made since

```
Can't authenticate
XHR failed loading: OPTIONS "https://stagingapi.whynot.earth/Account/AccessDenied?ReturnUrl=%2Fapi%2Fv0%2Fauthentication%2Fping".
```

I am hitting POST on this URL: https://stagingapi.whynot.earth/api/v0/authentication/login
this is my payload

`{email: "mailatharvasharma@gmail.com", password: "Password@1"}`
same issue when authenticating via OAuth

**Comment by StrangeWill** [comment] 2019-11-13 09:03
Auth handler from #48 is probably the cause if I had to guess at it, I'll see about having that patched sometime tomorrow.

**Comment by StrangeWill** [comment] 2019-11-13 09:06
@paulchrisluke that is technically a _different_ issue, not related to this one.

**Comment by StrangeWill** [comment] 2019-11-30 18:48
@atharva3010 should be fixed now, we just redirect back and pinging the auth endpoint should result in a 401 still.

**Closed by StrangeWill** 2019-11-30 18:48 UTC
Labels: .net, bug
